apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: streamr
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      imagePullSecrets:
        - name: do-registry
      containers:
      - name: user-service
        image: registry.digitalocean.com/streamr-registry/user-service:latest
        ports:
        - containerPort: 8082
        env:
        - name: SERVER_PORT
          value: "8082"
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: streamr-secrets
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: streamr-secrets
              key: DB_PORT
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: streamr-secrets
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: streamr-secrets
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: streamr-secrets
              key: DB_NAME
        - name: DB_SSLMODE
          valueFrom:
            secretKeyRef:
              name: streamr-secrets
              key: DB_SSLMODE
        # RabbitMQ
        - name: RABBITMQ_URL
          valueFrom:
            secretKeyRef:
              name: streamr-secrets
              key: RABBITMQ_URL
        - name: JWT_ACCESS_SECRET
          valueFrom:
            secretKeyRef:
              name: streamr-secrets
              key: JWT_ACCESS_SECRET
        envFrom:
        - configMapRef:
            name: streamr-config
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8082
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /health
            port: 8082
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: streamr
spec:
  selector:
    app: user-service
  ports:
  - port: 8082
    targetPort: 8082