---
# RabbitMQ Secret
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: livestream
type: Opaque
data:
  username: cmFiYml0X3VzZXI=  # rabbit_user
  password: cmFiYml0X3Bhc3M=  # rabbit_pass
  url: YW1xcDovL3JhYmJpdF91c2VyOnJhYmJpdF9wYXNzQHJhYmJpdG1xLXNlcnZpY2U6NTY3Mi8=  # amqp://rabbit_user:rabbit_pass@rabbitmq-service:5672/
