---
# JWT Secrets
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: livestream
type: Opaque
data:
  access-secret: Y2hhbmdlLXRoaXMtaW4tcHJvZHVjdGlvbg==  # change-this-in-production
  refresh-secret: Y2hhbmdlLXRoaXMtdG9vLWluLXByb2R1Y3Rpb24=  # change-this-too-in-production
